//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paid
    {
        public int ID { get; set; }
        public string PaidType { get; set; }
    }
}
