//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotesEntities : DbContext
    {
        public NotesEntities()
            : base("name=NotesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<Download> Downloads { get; set; }
        public DbSet<NoteCategory> NoteCategories { get; set; }
        public DbSet<NoteType> NoteTypes { get; set; }
        public DbSet<ReferenceData> ReferenceDatas { get; set; }
        public DbSet<SellerNote> SellerNotes { get; set; }
        public DbSet<SellerNotesAttachement> SellerNotesAttachements { get; set; }
        public DbSet<SellerNotesReportedIssue> SellerNotesReportedIssues { get; set; }
        public DbSet<SellerNotesReview> SellerNotesReviews { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
